### ISSUE TITLE
the script does not distinguish between disabled categories

### ISSUE THREAD

**Issue by hpvd** [dbashyal/Magento_Breadcrumbs#1]
extracted from comments on:
http://dltr.org/blog/magento/381/Magento-Force-Display-Full-Breadcrumb-Path

Pc  wrote at 01/06/15 05:04:44:

One small problem though: the script does not distinguish between disabled categories.

When a product is inside a disabled category AND another category which is enabled, the script might choose the disabled category (if it is first). On frontend there will be one breadcrumb missing (because that category is disabled).

Can the script be edited so it skips the disabled category and chooses the first enabled category?

**Comment by dbashyal** [comment]
added:

`$collection->addAttributeToFilter('is_active', array('eq'=>'1'));`

Hope that helps!
