### ISSUE TITLE
Products in multiple categories

### ISSUE THREAD

**Issue by sasoriza** [dbashyal/Magento_Breadcrumbs#3]
I have two problems with this modification, the first is already described here https://github.com/dbashyal/Magento_Breadcrumbs/issues/1

Even if this behavior could be fixed, how is determined which category will be displayed if various categories include the same product?

Maybe it woul be possible to completely disable the functionality, if a product occurs in more than one category. While this wouldn't be a perect solution, it would still be better as the current behavior.

**Comment by dbashyal** [comment]
Hi @sasoriza ,

With the latest update first deepest level active category will be chosen.
